const MARKET={
Global:{gl:'US',hl:'en-US',ceid:'US:en',reddit:''},APAC:{gl:'SG',hl:'en-SG',ceid:'SG:en',reddit:'Asia OR Japan OR Korea OR Singapore OR Australia OR India'},Japan:{gl:'JP',hl:'en',ceid:'JP:en',reddit:'Japan'},'South Korea':{gl:'KR',hl:'en',ceid:'KR:en',reddit:'Korea'},'Hong Kong':{gl:'HK',hl:'en-HK',ceid:'HK:en',reddit:'Hong Kong'},Singapore:{gl:'SG',hl:'en-SG',ceid:'SG:en',reddit:'Singapore'},Malaysia:{gl:'MY',hl:'en-MY',ceid:'MY:en',reddit:'Malaysia'},Thailand:{gl:'TH',hl:'en',ceid:'TH:en',reddit:'Thailand'},Vietnam:{gl:'VN',hl:'en',ceid:'VN:en',reddit:'Vietnam'},Taiwan:{gl:'TW',hl:'en',ceid:'TW:en',reddit:'Taiwan'},Indonesia:{gl:'ID',hl:'en',ceid:'ID:en',reddit:'Indonesia'},India:{gl:'IN',hl:'en-IN',ceid:'IN:en',reddit:'India'},'The Philippines':{gl:'PH',hl:'en-PH',ceid:'PH:en',reddit:'Philippines'},Australia:{gl:'AU',hl:'en-AU',ceid:'AU:en',reddit:'Australia'},'New Zealand':{gl:'NZ',hl:'en-NZ',ceid:'NZ:en',reddit:'New Zealand'}};

const LENS={
  Everything:'film OR movie OR cinema OR television OR TV OR streaming OR series OR drama OR anime OR advertising OR advertisement OR commercial OR fashion OR streetwear OR beauty OR cosmetics OR skincare OR makeup OR art OR design OR photography OR illustration OR architecture OR interiors OR aesthetic OR visual OR typography',
  'TV & Streaming':'television OR TV OR streaming OR series OR drama OR anime OR documentary OR episode OR show',
  Movies:'film OR movie OR cinema OR director OR cinematography OR trailer OR box office',
  Advertising:'advertising OR advertisement OR commercial OR brand campaign OR ad campaign OR creative agency OR campaign film OR brand spot',
  'Fashion & Beauty':'fashion OR apparel OR clothing OR streetwear OR beauty OR cosmetics OR skincare OR makeup OR runway OR couture OR designer OR fragrance OR perfume OR jewelry OR jewellery OR footwear OR handbag OR fashion week',
  'Art & Design':'art OR artist OR design OR photography OR illustration OR architecture OR interiors OR exhibition OR museum OR gallery OR installation',
  Aesthetics:'aesthetic OR visual style OR color trend OR colour trend OR typography OR graphic design OR photography trend OR visual trend'
};
const REQUIRED={
  Everything:['film','movie','cinema','television','streaming','series','drama','anime','advertising','advertisement','commercial','fashion','apparel','clothing','streetwear','beauty','cosmetics','skincare','makeup','runway','couture','designer','fragrance','perfume','jewelry','jewellery','footwear','handbag','art','artist','design','photography','illustration','architecture','interiors','exhibition','museum','gallery','aesthetic','typography'],
  'TV & Streaming':['television','tv ',' tv','streaming','series','drama','anime','documentary','episode','showrunner','tv show'],Movies:['film','movie','cinema','director','cinematography','trailer','box office','screenplay'],Advertising:['advertising','advertisement','commercial','ad campaign','brand campaign','creative agency','campaign film','brand spot','marketing campaign'],'Fashion & Beauty':['fashion','apparel','clothing','streetwear','beauty','cosmetics','skincare','skin care','makeup','make-up','runway','couture','designer','fragrance','perfume','jewelry','jewellery','footwear','handbag','fashion week','collection','beauty brand'],'Art & Design':['art ',' artist','artwork','design','photography','illustration','architecture','interiors','exhibition','museum','gallery','installation','sculpture','painting'],Aesthetics:['aesthetic','visual style','color trend','colour trend','typography','graphic design','photography trend','visual trend','palette','maximalism','minimalism']};

const LOCAL={
Japan:{gl:'JP',hl:'ja',ceid:'JP:ja',terms:{Everything:'映画 OR テレビ OR ドラマ OR アニメ OR 広告 OR CM OR ファッション OR 美容 OR 化粧品 OR アート OR デザイン OR 写真', 'TV & Streaming':'テレビ OR ドラマ OR 配信 OR アニメ OR 番組','Movies':'映画 OR シネマ OR 監督 OR 予告編','Advertising':'広告 OR CM OR キャンペーン OR クリエイティブ','Fashion & Beauty':'ファッション OR 美容 OR 化粧品 OR スキンケア OR メイク OR 香水 OR ジュエリー','Art & Design':'アート OR 美術 OR デザイン OR 写真 OR 建築 OR 展覧会','Aesthetics':'美学 OR ビジュアル OR 色 OR タイポグラフィ OR デザイン'},required:['映画','テレビ','ドラマ','アニメ','広告','cm','ファッション','美容','化粧品','アート','デザイン','写真','建築','展覧会']},
'South Korea':{gl:'KR',hl:'ko',ceid:'KR:ko',terms:{Everything:'영화 OR 드라마 OR TV OR 스트리밍 OR 광고 OR 패션 OR 뷰티 OR 화장품 OR 예술 OR 디자인 OR 사진','TV & Streaming':'드라마 OR 방송 OR TV OR 스트리밍 OR 예능','Movies':'영화 OR 감독 OR 시네마 OR 예고편','Advertising':'광고 OR 캠페인 OR 브랜드 광고 OR 크리에이티브','Fashion & Beauty':'패션 OR 뷰티 OR 화장품 OR 스킨케어 OR 메이크업 OR 향수','Art & Design':'예술 OR 미술 OR 디자인 OR 사진 OR 건축 OR 전시','Aesthetics':'미학 OR 비주얼 OR 색상 OR 타이포그래피 OR 디자인'},required:['영화','드라마','방송','스트리밍','광고','패션','뷰티','화장품','예술','미술','디자인','사진','건축','전시']},
'Hong Kong':{gl:'HK',hl:'zh-HK',ceid:'HK:zh-Hant',terms:{Everything:'電影 OR 電視 OR 劇集 OR 串流 OR 廣告 OR 時裝 OR 美容 OR 化妝品 OR 藝術 OR 設計 OR 攝影','TV & Streaming':'電視 OR 劇集 OR 串流 OR 節目','Movies':'電影 OR 導演 OR 戲院 OR 預告','Advertising':'廣告 OR 品牌活動 OR 宣傳片 OR 創意','Fashion & Beauty':'時裝 OR 美容 OR 化妝品 OR 護膚 OR 彩妝 OR 香水','Art & Design':'藝術 OR 設計 OR 攝影 OR 建築 OR 展覽','Aesthetics':'美學 OR 視覺 OR 色彩 OR 字體 OR 設計'},required:['電影','電視','劇集','串流','廣告','時裝','美容','化妝品','藝術','設計','攝影','建築','展覽']},
Taiwan:{gl:'TW',hl:'zh-TW',ceid:'TW:zh-Hant',terms:{Everything:'電影 OR 電視 OR 戲劇 OR 串流 OR 廣告 OR 時尚 OR 美妝 OR 化妝品 OR 藝術 OR 設計 OR 攝影','TV & Streaming':'電視 OR 戲劇 OR 串流 OR 節目','Movies':'電影 OR 導演 OR 戲院 OR 預告','Advertising':'廣告 OR 品牌活動 OR 宣傳片 OR 創意','Fashion & Beauty':'時尚 OR 美妝 OR 化妝品 OR 保養 OR 彩妝 OR 香水','Art & Design':'藝術 OR 設計 OR 攝影 OR 建築 OR 展覽','Aesthetics':'美學 OR 視覺 OR 色彩 OR 字體 OR 設計'},required:['電影','電視','戲劇','串流','廣告','時尚','美妝','化妝品','藝術','設計','攝影','建築','展覽']},
Thailand:{gl:'TH',hl:'th',ceid:'TH:th',terms:{Everything:'ภาพยนตร์ OR ละคร OR ทีวี OR สตรีมมิง OR โฆษณา OR แฟชั่น OR ความงาม OR เครื่องสำอาง OR ศิลปะ OR ออกแบบ OR ถ่ายภาพ','TV & Streaming':'ละคร OR ทีวี OR สตรีมมิง OR ซีรีส์','Movies':'ภาพยนตร์ OR หนัง OR ผู้กำกับ OR ตัวอย่าง','Advertising':'โฆษณา OR แคมเปญ OR ครีเอทีฟ','Fashion & Beauty':'แฟชั่น OR ความงาม OR เครื่องสำอาง OR สกินแคร์ OR เมคอัพ OR น้ำหอม','Art & Design':'ศิลปะ OR ออกแบบ OR ถ่ายภาพ OR สถาปัตยกรรม OR นิทรรศการ','Aesthetics':'สุนทรียะ OR ภาพ OR สี OR ตัวอักษร OR ออกแบบ'},required:['ภาพยนตร์','ละคร','ทีวี','สตรีมมิง','โฆษณา','แฟชั่น','ความงาม','เครื่องสำอาง','ศิลปะ','ออกแบบ','ถ่ายภาพ']},
Vietnam:{gl:'VN',hl:'vi',ceid:'VN:vi',terms:{Everything:'phim OR truyền hình OR phim bộ OR quảng cáo OR thời trang OR làm đẹp OR mỹ phẩm OR nghệ thuật OR thiết kế OR nhiếp ảnh','TV & Streaming':'truyền hình OR phim bộ OR streaming OR chương trình','Movies':'phim OR điện ảnh OR đạo diễn OR trailer','Advertising':'quảng cáo OR chiến dịch OR sáng tạo','Fashion & Beauty':'thời trang OR làm đẹp OR mỹ phẩm OR chăm sóc da OR trang điểm OR nước hoa','Art & Design':'nghệ thuật OR thiết kế OR nhiếp ảnh OR kiến trúc OR triển lãm','Aesthetics':'thẩm mỹ OR hình ảnh OR màu sắc OR kiểu chữ OR thiết kế'},required:['phim','truyền hình','quảng cáo','thời trang','làm đẹp','mỹ phẩm','nghệ thuật','thiết kế','nhiếp ảnh','kiến trúc','triển lãm']},
Indonesia:{gl:'ID',hl:'id',ceid:'ID:id',terms:{Everything:'film OR televisi OR serial OR streaming OR iklan OR mode OR kecantikan OR kosmetik OR seni OR desain OR fotografi','TV & Streaming':'televisi OR serial OR streaming OR acara','Movies':'film OR bioskop OR sutradara OR trailer','Advertising':'iklan OR kampanye OR kreatif','Fashion & Beauty':'mode OR fesyen OR kecantikan OR kosmetik OR skincare OR makeup OR parfum','Art & Design':'seni OR desain OR fotografi OR arsitektur OR pameran','Aesthetics':'estetika OR visual OR warna OR tipografi OR desain'},required:['film','televisi','serial','streaming','iklan','mode','fesyen','kecantikan','kosmetik','seni','desain','fotografi','arsitektur','pameran']},
Malaysia:{gl:'MY',hl:'ms',ceid:'MY:ms',terms:{Everything:'filem OR televisyen OR drama OR penstriman OR iklan OR fesyen OR kecantikan OR kosmetik OR seni OR reka bentuk OR fotografi','TV & Streaming':'televisyen OR drama OR penstriman OR siri','Movies':'filem OR pawagam OR pengarah OR treler','Advertising':'iklan OR kempen OR kreatif','Fashion & Beauty':'fesyen OR kecantikan OR kosmetik OR penjagaan kulit OR solekan OR minyak wangi','Art & Design':'seni OR reka bentuk OR fotografi OR seni bina OR pameran','Aesthetics':'estetika OR visual OR warna OR tipografi OR reka bentuk'},required:['filem','televisyen','drama','penstriman','iklan','fesyen','kecantikan','kosmetik','seni','reka bentuk','fotografi','pameran']},
India:{gl:'IN',hl:'hi',ceid:'IN:hi',terms:{Everything:'फिल्म OR टीवी OR सीरीज OR स्ट्रीमिंग OR विज्ञापन OR फैशन OR सौंदर्य OR कॉस्मेटिक्स OR कला OR डिजाइन OR फोटोग्राफी','TV & Streaming':'टीवी OR सीरीज OR स्ट्रीमिंग OR धारावाहिक','Movies':'फिल्म OR सिनेमा OR निर्देशक OR ट्रेलर','Advertising':'विज्ञापन OR अभियान OR क्रिएटिव','Fashion & Beauty':'फैशन OR सौंदर्य OR कॉस्मेटिक्स OR स्किनकेयर OR मेकअप OR परफ्यूम','Art & Design':'कला OR डिजाइन OR फोटोग्राफी OR वास्तुकला OR प्रदर्शनी','Aesthetics':'सौंदर्यशास्त्र OR विजुअल OR रंग OR टाइपोग्राफी OR डिजाइन'},required:['फिल्म','टीवी','सीरीज','स्ट्रीमिंग','विज्ञापन','फैशन','सौंदर्य','कॉस्मेटिक्स','कला','डिजाइन','फोटोग्राफी']},
'The Philippines':{gl:'PH',hl:'fil',ceid:'PH:fil',terms:{Everything:'pelikula OR telebisyon OR serye OR streaming OR patalastas OR fashion OR kagandahan OR kosmetiko OR sining OR disenyo OR potograpiya','TV & Streaming':'telebisyon OR serye OR streaming OR palabas','Movies':'pelikula OR sine OR direktor OR trailer','Advertising':'patalastas OR kampanya OR malikhaing','Fashion & Beauty':'fashion OR moda OR kagandahan OR kosmetiko OR skincare OR makeup OR pabango','Art & Design':'sining OR disenyo OR potograpiya OR arkitektura OR eksibisyon','Aesthetics':'estetika OR biswal OR kulay OR tipograpiya OR disenyo'},required:['pelikula','telebisyon','serye','streaming','patalastas','fashion','moda','kagandahan','kosmetiko','sining','disenyo','potograpiya']},
Singapore:{gl:'SG',hl:'zh-SG',ceid:'SG:zh-Hans',terms:{Everything:'电影 OR 电视 OR 剧集 OR 串流 OR 广告 OR 时尚 OR 美妆 OR 化妆品 OR 艺术 OR 设计 OR 摄影','TV & Streaming':'电视 OR 剧集 OR 串流 OR 节目','Movies':'电影 OR 导演 OR 影院 OR 预告','Advertising':'广告 OR 品牌活动 OR 宣传片 OR 创意','Fashion & Beauty':'时尚 OR 美妆 OR 化妆品 OR 护肤 OR 彩妆 OR 香水','Art & Design':'艺术 OR 设计 OR 摄影 OR 建筑 OR 展览','Aesthetics':'美学 OR 视觉 OR 色彩 OR 字体 OR 设计'},required:['电影','电视','剧集','串流','广告','时尚','美妆','化妆品','艺术','设计','摄影','建筑','展览']},
Australia:{gl:'AU',hl:'en-AU',ceid:'AU:en',terms:null,required:null},'New Zealand':{gl:'NZ',hl:'en-NZ',ceid:'NZ:en',terms:null,required:null}
};
const APAC_LOCAL=['Japan','South Korea','Hong Kong','Singapore','Malaysia','Thailand','Vietnam','Taiwan','Indonesia','India','The Philippines','Australia','New Zealand'];

const GEO=new Set('japan japanese tokyo osaka kyoto okinawa korea korean seoul hong kong singapore malaysia malaysian thailand thai bangkok vietnam vietnamese taiwan taiwanese indonesia indonesian india indian philippines philippine australia australian new zealand asia asian apac america american united states uk britain british europe european china chinese'.split(/\s+/));
const GENERIC=new Set('launch launches launched unveils unveiled reveals revealed expands expansion enters market markets brand brands company companies latest new announces announced opens opening store stores report reports trend trends style styles collection collections'.split(/\s+/));
const STOP=new Set('the a an and or but if to of in on for with from at by as is are was were be been this that these those it its their our your new latest says after before about into over under more most how why what when where who has have had will would could should can may might not no up out first last today year years week weeks day days live update report reports news world people one two three just now through against around between during via also still get gets got make makes made take takes took big top best much many some any all other another same such own local national international global market markets company companies government governments president prime minister police court official officials state states city cities country countries'.split(/\s+/));
const decode=s=>String(s||'').replace(/<!\[CDATA\[|\]\]>/g,'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>'),strip=s=>decode(s).replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
function rssItems(xml){return [...xml.matchAll(/<item>([\s\S]*?)<\/item>/g)].map(m=>{const x=m[1],pick=t=>decode((x.match(new RegExp(`<${t}[^>]*>([\\s\\S]*?)<\\/${t}>`))||[])[1]||'');return{title:strip(pick('title')).replace(/\s+-\s+[^-]{2,60}$/,''),url:strip(pick('link')),date:strip(pick('pubDate')),source:strip(pick('source')),traffic:strip((x.match(/<ht:approx_traffic>([\s\S]*?)<\/ht:approx_traffic>/)||[])[1]||'')}})}
function withinLast24Hours(row){const d=new Date(row.date),age=Date.now()-d.getTime();return !isNaN(d)&&age>=0&&age<=86400000}
function clean(s=''){return s.toLowerCase().replace(/[^\p{L}\p{N}\s]/gu,' ').replace(/\s+/g,' ').trim()}
function lensRelevant(title,lens){const t=' '+clean(title)+' ';return (REQUIRED[lens]||REQUIRED.Everything).some(term=>t.includes(term))}
function localRelevant(title,cfg){if(!cfg.required)return lensRelevant(title,'Everything');const t=clean(title);return cfg.required.some(term=>t.includes(clean(term)))}
function usefulWord(w){return w.length>2&&!STOP.has(w)&&!GEO.has(w)&&!GENERIC.has(w)&&!/^\d+$/.test(w)}
function phrases(title){const words=clean(title).split(' ').filter(usefulWord),out=[];for(let i=0;i<words.length;i++){if(words[i].length>=4)out.push(words[i]);if(i<words.length-1&&words[i].length+words[i+1].length>8)out.push(words[i]+' '+words[i+1]);if(i<words.length-2&&words[i].length+words[i+1].length+words[i+2].length>14)out.push(words[i]+' '+words[i+1]+' '+words[i+2])}return [...new Set(out)]}
function trafficNumber(s=''){const n=parseFloat(String(s).replace(/[^0-9.]/g,''))||0,low=s.toLowerCase();return n*(low.includes('m')?1e6:low.includes('k')?1e3:1)}
async function fetchText(url,ms=8000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,headers:{'User-Agent':'Mozilla/5.0 (compatible; ZeitgeistRadar/1.0)'}});if(!r.ok)throw new Error(String(r.status));return await r.text()}finally{clearTimeout(t)}}
async function fetchJSON(url,ms=8000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,headers:{'User-Agent':'ZeitgeistRadar/1.0 (+https://zeitgeist-radar.vercel.app)'}});if(!r.ok)throw new Error(String(r.status));return await r.json()}finally{clearTimeout(t)}}
function add(map,name,source,weight,evidence){const key=clean(name);if(!key||key.length<4)return;let s=map.get(key);if(!s){s={name:name.trim(),sources:new Set(),weights:{},evidence:[],mentions:0,searchVolume:0,redditScore:0};map.set(key,s)}s.sources.add(source);s.weights[source]=(s.weights[source]||0)+weight;s.mentions++;if(source==='Search')s.searchVolume+=weight;if(source==='Reddit')s.redditScore+=weight;if(evidence&&!s.evidence.some(e=>e.title===evidence.title)&&s.evidence.length<8)s.evidence.push(evidence)}
function clusterLabel(s){const counts=new Map(),bigrams=new Map();for(const e of s.evidence){const ws=clean(e.title).split(' ').filter(usefulWord);for(const w of ws)counts.set(w,(counts.get(w)||0)+1);for(let i=0;i<ws.length-1;i++){const b=ws[i]+' '+ws[i+1];bigrams.set(b,(bigrams.get(b)||0)+1)}}const bestBi=[...bigrams.entries()].filter(([,n])=>n>=2).sort((a,b)=>b[1]-a[1]||b[0].length-a[0].length)[0];if(bestBi)return bestBi[0].replace(/\b\w/g,c=>c.toUpperCase());const bestWords=[...counts.entries()].sort((a,b)=>b[1]-a[1]).slice(0,2).map(x=>x[0]);if(bestWords.length)return bestWords.join(' ').replace(/\b\w/g,c=>c.toUpperCase());return s.name.replace(/\b\w/g,c=>c.toUpperCase())}
function classify(score,sourceCount,searchVolume,redditScore){if(sourceCount>=3&&score>=75)return'Breaking Out';if(sourceCount>=2&&score>=60)return'Rising';if(score>=52)return'Sustained';if(searchVolume>0||redditScore>0)return'Weak Signal';return'Cooling'}
async function localRowsFor(name,lens){const cfg=LOCAL[name];if(!cfg)return[];const q=cfg.terms?(cfg.terms[lens]||cfg.terms.Everything):(LENS[lens]||LENS.Everything);const u=new URL('https://news.google.com/rss/search');u.searchParams.set('q',`(${q}) when:1d`);u.searchParams.set('hl',cfg.hl);u.searchParams.set('gl',cfg.gl);u.searchParams.set('ceid',cfg.ceid);return rssItems(await fetchText(u)).filter(withinLast24Hours).filter(r=>localRelevant(r,cfg)).slice(0,24).map(r=>({...r,market:name}))}

module.exports=async function(req,res){const market=req.query.market||'Global',lens=req.query.lens||'Everything',m=MARKET[market]||MARKET.Global,map=new Map(),status={Search:'offline',News:'offline',Reddit:'offline','Visual Culture':'offline','Local Language':'offline'};let counts={Search:0,News:0,Reddit:0,'Visual Culture':0,'Local Language':0};const jobs=[],visualQuery=LENS[lens]||LENS.Everything;
jobs.push((async()=>{try{const u=new URL('https://trends.google.com/trending/rss');u.searchParams.set('geo',m.gl);const rows=rssItems(await fetchText(u)).filter(withinLast24Hours).filter(r=>lensRelevant(r.title,lens)).slice(0,40);counts.Search=rows.length;status.Search=rows.length?'live':'empty';for(const r of rows){const vol=trafficNumber(r.traffic);for(const p of phrases(r.title))add(map,p,'Search',Math.max(8,Math.log10(vol+10)*8),{source:'Search',title:r.title,url:`https://trends.google.com/trending?geo=${m.gl}`,meta:r.traffic||'Trending Now'})}}catch(e){status.Search='unavailable'}})());
jobs.push((async()=>{try{const q=[`(${visualQuery})`,m.reddit?`(${m.reddit})`:'','when:1d'].filter(Boolean).join(' '),u=new URL('https://news.google.com/rss/search');u.searchParams.set('q',q);u.searchParams.set('hl',m.hl);u.searchParams.set('gl',m.gl);u.searchParams.set('ceid',m.ceid);const rows=rssItems(await fetchText(u)).filter(withinLast24Hours).filter(r=>lensRelevant(r.title,lens)).slice(0,100);counts.News=rows.length;status.News=rows.length?'live':'empty';for(const r of rows)for(const p of phrases(r.title))add(map,p,'News',6,{source:'News',title:r.title,url:r.url,meta:r.source||''})}catch(e){status.News='unavailable'}})());
jobs.push((async()=>{try{const q=[m.reddit,visualQuery].filter(Boolean).join(' '),u=new URL('https://www.reddit.com/search.json');u.searchParams.set('q',q);u.searchParams.set('sort','hot');u.searchParams.set('t','day');u.searchParams.set('limit','75');const j=await fetchJSON(u),rows=(((j||{}).data||{}).children||[]).filter(x=>lensRelevant((x.data||{}).title||'',lens));counts.Reddit=rows.length;status.Reddit=rows.length?'live':'empty';for(const x of rows){const d=x.data||{},score=Math.log10((d.score||0)+10)*8;for(const p of phrases(d.title||''))add(map,p,'Reddit',Math.max(5,score),{source:'Reddit',title:d.title||'',url:d.permalink?'https://www.reddit.com'+d.permalink:'',meta:`${d.score||0} pts · r/${d.subreddit||''}`})}}catch(e){status.Reddit='unavailable'}})());
jobs.push((async()=>{try{const q=[`(${visualQuery})`,m.reddit?`(${m.reddit})`:'','when:1d'].filter(Boolean).join(' '),u=new URL('https://news.google.com/rss/search');u.searchParams.set('q',q);u.searchParams.set('hl',m.hl);u.searchParams.set('gl',m.gl);u.searchParams.set('ceid',m.ceid);const rows=rssItems(await fetchText(u)).filter(withinLast24Hours).filter(r=>lensRelevant(r.title,lens)).slice(0,100);counts['Visual Culture']=rows.length;status['Visual Culture']=rows.length?'live':'empty';for(const r of rows)for(const p of phrases(r.title))add(map,p,'Visual Culture',7,{source:'Visual Culture',title:r.title,url:r.url,meta:r.source||'Visual culture coverage'})}catch(e){status['Visual Culture']='unavailable'}})());
jobs.push((async()=>{try{const targets=market==='APAC'?APAC_LOCAL:(LOCAL[market]?[market]:[]);if(!targets.length){status['Local Language']='n/a';return}const results=await Promise.allSettled(targets.map(n=>localRowsFor(n,lens)));const rows=results.flatMap(x=>x.status==='fulfilled'?x.value:[]);counts['Local Language']=rows.length;status['Local Language']=rows.length?'live':'empty';for(const r of rows)for(const p of phrases(r.title))add(map,p,'Local Language',8,{source:'Local Language',title:r.title,url:r.url,meta:`${r.market} · ${r.source||'local-language source'}`})}catch(e){status['Local Language']='unavailable'}})());
await Promise.allSettled(jobs);
let signals=[...map.values()].map(s=>{const sourceCount=s.sources.size,raw=Object.values(s.weights).reduce((a,b)=>a+b,0),convergence=(sourceCount-1)*20,score=Math.round(Math.min(100,raw+convergence)),reach=Math.round(Math.min(100,30+sourceCount*15+Math.log10(s.searchVolume+s.redditScore+10)*10));return{name:clusterLabel(s),score,reach,sourceCount,sources:[...s.sources],classification:classify(score,sourceCount,s.searchVolume,s.redditScore),searchVolume:Math.round(s.searchVolume),redditScore:Math.round(s.redditScore),mentions:s.mentions,evidence:s.evidence}}).filter(s=>s.score>=28&&s.name.length>3).sort((a,b)=>(b.sourceCount-a.sourceCount)||(b.score-a.score)).filter((s,i,a)=>a.findIndex(x=>clean(x.name)===clean(s.name))===i).slice(0,20);
if(!signals.length)signals=[{name:'Awaiting Relevant Visual Signal',score:25,reach:25,sourceCount:0,sources:[],classification:'Weak Signal',searchVolume:0,redditScore:0,mentions:0,evidence:[]}];res.setHeader('Cache-Control','s-maxage=300, stale-while-revalidate=600');return res.status(200).json({market,lens,generatedAt:new Date().toISOString(),windowHours:24,scope:'visual-culture-only',counts,status,totalItems:Object.values(counts).reduce((a,b)=>a+b,0),signals});};
